<?php
/**
 * Cliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cliente extends BaseCliente
{

	public function insert($data){
	
		try{
			$tabela = getTableValues($this,$data);
			$tabela->save();
			return true;
		}catch(Exception $e){
			return false;
		}
	}
	
	public function update($data){
	
		try{
			if(!is_numeric($data['id']))
				return false;
			
			$cliente = $this->getCliente($data['id']);
			if($cliente == null) return false;
			
			$cliente = getTableValues($cliente,$data,true);
			$cliente->save();
			return true;
		}catch(Exception $e){
			return false;
		}
	}
	
	public function remove($id){
		
		try{
			if(isset($id) && !is_numeric($id))
				return false;
			
			$q = Doctrine_Query::create()
				->delete('Cliente c')
				->where('c.id = ?',array($id));
			$rows = $q->execute();
			return ($rows > 0);
		}catch(Exception $e){
			return false;
		}
	}
	
	public function getAll(){
		
		try{			
			$clienteList = Doctrine_Core::getTable('Cliente')->findAll();
			if($clienteList->count() > 0)
				return $clienteList;
			return null;
		}catch(Exception $e){
			return null;
		}
	}
	
	public function getCliente($id){
		
		try{			
			$cliente = Doctrine_Core::getTable('Cliente')->find($id);
			if($cliente != null)
				return $cliente;
			return null;
		}catch(Exception $e){
			return null;
		}
	}
}